name: pharma
services:
  pharma-db:
    image: 'postgres:latest'
    container_name: pharma-database
    env_file:
      - app.env
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    networks:
      - pharma

  pharma-cache:
    image: 'redis:latest'
    container_name: pharma-cache
    hostname: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6379:6379"
    restart: always
    networks:
      - pharma

  app:
    container_name: pharma
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app.env
    ports:
      - "8083:8084"
    depends_on:
      pharma-db:
        condition: service_healthy
      pharma-cache:
        condition: service_healthy
    restart: no
    networks:
      - pharma

networks:
  pharma:
    attachable: true
    name: pharma
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/112

volumes:
  postgres-db:
    driver: local