name: aftas
services:
  aftas-db:
    image: 'postgres:latest'
    container_name: database
    environment:
      - POSTGRES_DB=${APP_DB_NAME}
      - POSTGRES_PASSWORD=${APP_DB_PASS}
      - POSTGRES_USER=${APP_DB_USER}
      - PGDATA=/data/postgres
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    networks:
      - aftas

  aftas-cache:
    image: 'redis:latest'
    container_name: jobinow-cache
    hostname: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6379:6379"
    restart: always
    networks:
      - aftas

  app:
    container_name: aftas
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8084"
    depends_on:
      aftas-db:
        condition: service_healthy
      aftas-cache:
        condition: service_healthy
    restart: no
    networks:
      - aftas

networks:
  aftas:
    attachable: true
    name: aftas
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/112


volumes:
  postgres-db:
    driver: local
